name: gee3
on: push

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: auther
        run: |
          eval 'set +o history' 2>/dev/null || setopt HIST_IGNORE_SPACE 2>/dev/null
          touch ~/.gitcookies
          chmod 0600 ~/.gitcookies
          git config --global http.cookiefile ~/.gitcookies
          tr , \\t <<\__END__ >>~/.gitcookies
          ${{secrets.EECRED}}
          __END__
          eval 'set -o history' 2>/dev/null || unsetopt HIST_IGNORE_SPACE 2>/dev/null
      - name: commit files
        run: |
          cwd=$(pwd)
          RepoArray=("terra2018" "agu2018" "Dam" "default")
          today=$(date +"%Y-%m-%d")
          cd $cwd
          for val in ${RepoArray[*]}
            do
              if [ -d "$val" ]; then rm -Rf $val; fi
              git clone "https://earthengine.googlesource.com/users/sat-io/$val" && rm -rf $val/.git
            done
          cd $cwd
          ls -l -a
