name: gee3up
on: 
  push:
    branches:
      - main
  schedule:
    - cron:  '15 0 * * *'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
        with:
          ref: main
      - name: auther
        run: |
          eval 'set +o history' 2>/dev/null || setopt HIST_IGNORE_SPACE 2>/dev/null
          touch ~/.gitcookies
          chmod 0600 ~/.gitcookies
          git config --global http.cookiefile ~/.gitcookies
          tr , \\t <<\__END__ >>~/.gitcookies
          ${{secrets.EECRED}}
          __END__
          eval 'set -o history' 2>/dev/null || unsetopt HIST_IGNORE_SPACE 2>/dev/null
      - name: commit changes
        continue-on-error: true
        run: |
          cwd=$(pwd)
          RepoArray=("test" "terra2018" "agu2018" "default")
          today=$(date +"%Y-%m-%d")
          cd $cwd
          rm -rf $cwd/.git
          for val in ${RepoArray[*]}
            do
              if [ -d "$val" ]; then rm -Rf $val; fi
              git clone "https://earthengine.googlesource.com/users/sat-io/$val"
              cd $val
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add -A
              git commit -m "updated datasets ${today}"
              git remote add origin "https://earthengine.googlesource.com/users/sat-io/$val"
              git push origin master --force
              cd ..
            done
          cd $cwd
